### ISSUE TITLE
Need some way to skip cases in manage_cases ui

### ISSUE THREAD

**Issue by hadley** [r-lib/vdiffr#13]
So you can see the others without validating

**Comment by lionel-** [comment]
Do you mean a shortcut to navigate to the next case? Or remove the case from the dropdown list so that you can safely use "validate all"?

**Comment by hadley** [comment]
Just move to the next case

**Comment by clauswilke** [comment]
I agree. Was just about to file an issue on this topic. I think two additional buttons would do, e.g. "skip" and "back". Having to navigate through the failed cases via drop-down is awkward.

Use case: I have a bunch of cases that fail and I want to see what the issue is before I decide whether they should be validated or not.

**Comment by lionel-** [comment]
Undo would unvalidate and the case would show up as "New".

**Comment by nathancday** [comment]
I know its not tidy-dev-day anymore but would you still like a PR for this issue? I'd like to keep contributing to this package and think I could help here.

**Comment by lionel-** [comment]
That'd be awesome!

I think some keyboard shortcuts would be helpful as well, e.g. right arrow to switch to next case and down arrow to switch to next category.

**Comment by nathancday** [comment]
Great! I'll start working on these buttons along with key-bindings from #64.
