### ISSUE TITLE
Shiny app should exit when all cases validated

### ISSUE THREAD

**Issue by hadley** [r-lib/vdiffr#24]

**Comment by karawoo** [comment]
@lionel- and I talked about this and it's not clear what the right exiting behavior is, since the app currently shows validated cases in addition to cases that need validation. We could quit when the only cases that remain are validated ones, but then it doesn't make a lot of sense to show them. If the validated cases aren't useful to see, we could remove them. In that case if you ran `manage_cases()` and there was nothing to validate, the app would immediately quit, which might be confusing. We think leaving things as-is (with the "quit" button that was already added) is probably sufficient, but @hadley do you have other opinions?

**Comment by hadley** [comment]
Yeah, that makes sense to me

**Comment by lionel-** [comment]
Closing this since the Shiny app has been removed from vdiffr in favour of `testthat::snapshot_review()`.
