### ISSUE TITLE
Think about testing of raster images

### ISSUE THREAD

**Issue by lionel-** [r-lib/vdiffr#31]

**Comment by cpsievert** [comment]
I imagine the idea here is, if the svg diff fails, then diff the raster images and only report a failure if both diffs fail? 

I'd love to have this in addition to some way to specify the diffing algorithm as well as an acceptable threshold.

FWIW, I was thinking of starting a PR doing that via `magick::image_read_svg()` and `magick::image_compare_dist()`, but not sure if Cairo would be better.

**Comment by lionel-** [comment]
The problem with using magick for bitmap diffing is that the threshold might have to be set up to a very high level to avoid false positive failures due to variations in font rendering across systems. Then we'll get false negatives.

I wonder if we could strip all the text boxes from text. The textboxes have already be shaped and their extents are hardcoded in the SVG, so really only the rendering could cause failures. Then the procedure would be:

* Detect that a svg embeds a raster image.
* Strip the raster images and perform text comparison of the SVG.
* Strip the text and perform bitmap comparison of the SVG with magick.

cc @jeroen

**Comment by vandenman** [comment]
I've created a minimal working example to implement tolerance based testing at https://github.com/vandenman/vdiffr/tree/bitmap_comparison

The principle is that if the SVG files are not exactly equal, a tolerance based test is done, to see if the figures partially match.

A test could look somewhat like this:
```r
test_that("plots_are_equal", {

  library(ggplot2)

  set.seed(1)
  x <- rnorm(10)
  y <- rnorm(10)
  plot_0 <- qplot(x = x, y = y)

  expect_doppelganger(
    "myplot_partial",
    plot_0,
    "",
    partial_match       = TRUE,
    partial_match_is_ok = TRUE,
    partial_tolerance   = 1,
    partial_fun         = vdiffr:::compare_abs_difference
  )

})
```

- `partial_match` enables whether the tolerance based test is done at all.
- `partial_match_is_ok` enables whether partial matches are counted as a mismatch.
- `partial_tolerance` sets a numeric tolerance for a test.
- `partial_fun`, a function to use for partial testing.

Rather than setting these arguments for each test individually, I've (ab)used `options` to allow one to specify these globally:

```r
# default arguments to case_compare
partial_match       = getOption("vdiffr.partial_match", FALSE),
partial_match_is_ok = getOption("vdiffr.partial_match_is_ok", FALSE),
partial_tolerance   = getOption("vdiffr.partial_match_tolerance", 1),
partial_fun         = getOption("vdiffr.partial_match_fun", compare_abs_difference)
```

The remaining question is how to set `partial_fun` and `partial_tolerance`. Personally, I don't think there's a one size fits all solution to this. A contour plot or heatmap may require a different comparison function than a line plot. `partial_fun` could also be adjusted to strip the text from an SVG before rendering it into a bitmap.



My adjustments are good enough for my own purposes, but I'd be happy to open a PR (and implement any suggested changes) if you are open to that. I understand that you may have your own roadmap to handle this issue.

**Comment by lionel-** [comment]
Discussion moved to #63.
